

TARGET:=usbpd_fw

CH32V003FUN:=ch32v003fun/ch32v003fun
MINICHLINK:=ch32v003fun/minichlink
include ch32v003fun/ch32v003fun/ch32v003fun.mk

all : build_fw


build_fw: build
	rm -f $(TARGET).elf $(TARGET).hex $(TARGET).lst $(TARGET).map $(TARGET).hex 

flash : cv_flash
clean : cv_clean
